export const CFG={width:820,height:520,birdX:190,radius:13,gravity:760,flapVelocity:-245,speed:130,pipeWidth:64,gap:190,spacing:255,step:.16,maxDecisions:220};
export const PRICE=.042/1e6;
export function fresh(seed=1){let n=seed>>>0;const random=()=>{n=(Math.imul(1664525,n)+1013904223)>>>0;return n/4294967296;};return {id:crypto.randomUUID(),seed,time:0,y:250,velocity:0,score:0,alive:true,steps:0,pipes:Array.from({length:20},(_,i)=>({id:i,x:480+i*CFG.spacing,center:150+random()*220,passed:false})),usage:{calls:0,tokens:0,cost:0,ms:0},last:null,history:[]};}
export function simulate(game,action,duration=CFG.step){
 const g=structuredClone(game);if(!g.alive)return g;if(action==='flap')g.velocity=CFG.flapVelocity;
 const n=Math.ceil(duration*120),dt=duration/n;
 for(let i=0;i<n&&g.alive;i++){
  g.velocity+=CFG.gravity*dt;g.y+=g.velocity*dt;g.time+=dt;for(const p of g.pipes)p.x-=CFG.speed*dt;
  if(g.y-CFG.radius<=0||g.y+CFG.radius>=CFG.height)g.alive=false;
  for(const p of g.pipes){if(p.x<CFG.birdX+CFG.radius&&p.x+CFG.pipeWidth>CFG.birdX-CFG.radius&&(g.y-CFG.radius<p.center-CFG.gap/2||g.y+CFG.radius>p.center+CFG.gap/2))g.alive=false;if(!p.passed&&p.x+CFG.pipeWidth<CFG.birdX-CFG.radius){p.passed=true;g.score++;}}
 }
 return g;
}
export function observation(g){const next=g.pipes.find(p=>p.x+CFG.pipeWidth>=CFG.birdX-CFG.radius),round=n=>Math.round(n*10)/10;return {coordinateSystem:'Y grows DOWN. Negative velocity moves up. Positive velocity falls.',bird:{y:round(g.y),verticalVelocity:round(g.velocity),radius:CFG.radius},world:{top:0,bottom:CFG.height,gravity:CFG.gravity,flapVelocity:CFG.flapVelocity},nextPipe:next?{distanceToFront:round(next.x-CFG.birdX),distanceToBack:round(next.x+CFG.pipeWidth-CFG.birdX),safeBirdCenterMin:round(next.center-CFG.gap/2+CFG.radius+8),safeBirdCenterMax:round(next.center+CFG.gap/2-CFG.radius-8),gapCenter:round(next.center),secondsUntilFront:round(Math.max(0,(next.x-CFG.birdX-CFG.radius)/CFG.speed))}:null,predictions:Object.fromEntries(['flap','coast'].map(action=>{const soon=simulate(g,action,.32);return [action,{yAfter320ms:round(soon.y),verticalVelocityAfter320ms:round(soon.velocity),collisionWithin320ms:!soon.alive}];}))};}
export function requestFor(g){
 const o=observation(g),center=o.nextPipe?.gapCenter??260;
 const describe=(y,v)=>`${Math.abs(y-center)<18?'Aligned with':y<center?'ABOVE':'BELOW'} the target opening center${Math.abs(y-center)<18?'':` by ${Math.round(Math.abs(y-center))} pixels`}. ${v<-35?'RISING upward':v>35?'FALLING downward':'Nearly level'}.`;
 const candidates=Object.fromEntries(Object.entries(o.predictions).map(([action,p])=>[action,`${action==='flap'?'Push upward once':'Release the flap button and let gravity act'}. In 320 ms: ${describe(p.yAfter320ms,p.verticalVelocityAfter320ms)} ${p.collisionWithin320ms?'DANGER: this trajectory collides within 320 ms.':'No collision within 320 ms.'}`]));
 return {model:'jev-1.13.0',state:{goal:'Navigate safely through the next pipe opening. Keep near its center, avoiding excessive upward or downward momentum.',currentPosition:describe(g.y,g.velocity),openingArrivesInSeconds:o.nextPipe?.secondsUntilFront,options:candidates},questions:{move:{type:'choice',instructions:'Choose the safer next Flappy Bird move using the supplied current position and projected outcomes. Flapping pushes UP; coasting lets gravity pull DOWN. When above the target opening, stop pushing upward and descend toward it. When falling below the opening, flap to recover upward. Consider momentum to avoid overshooting. Avoid a predicted collision if the other choice is safe. Aim near the opening center. Forecasts assume no further input for 320 ms; you will choose again after 160 ms.',criteria:candidates}}};
}
export function parse(raw){const a=raw.answers?.move;if(a?.type!=='choice'||!['flap','coast'].includes(a.choice)||!Number.isFinite(a.confidence)||!Number.isSafeInteger(raw.usage?.input_tokens)||raw.usage.input_tokens<0)throw Error('Jev returned an invalid flight decision.');return {action:a.choice,confidence:a.confidence,probabilities:a.probabilities,tokens:raw.usage.input_tokens};}
export function applyDecision(g,decision,ms){const before={y:g.y,velocity:g.velocity,time:g.time};const next=simulate(g,decision.action);next.steps++;next.last={...decision,ms,before,observation:observation(g)};next.usage={calls:g.usage.calls+1,tokens:g.usage.tokens+decision.tokens,cost:g.usage.cost+decision.tokens*PRICE,ms:g.usage.ms+ms};next.history=[{step:next.steps,action:decision.action,y:Math.round(next.y),ms},...g.history].slice(0,12);if(next.steps>=CFG.maxDecisions||next.score>=10)next.finished=true;return next;}
